server.port=8080

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://priyanka_sharma_16:06HzIuEXl3lIoM6L@cluster0.azjhv2j.mongodb.net/statemanager?retryWrites=true&w=majority


# JWT
jwt.secret=your-super-secret-key-change-this-in-production-min-32-chars
jwt.expiration=86400000

# Logging
logging.level.com.statemanager=DEBUG
logging.level.org.springframework.security=INFO

# Springdoc / Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# CORS
app.cors.allowed-origins=http://127.0.0.1:3000,http://localhost:3000

